/**
 * FTFP API
 * Finance tools for people
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ModelsTickerHistory from './model/ModelsTickerHistory';
import ModelsTickerHistoryQuery from './model/ModelsTickerHistoryQuery';
import DataApi from './api/DataApi';


/**
* Finance_tools_for_people.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FtfpApi = require('index'); // See note below*.
* var xxxSvc = new FtfpApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FtfpApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FtfpApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FtfpApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ModelsTickerHistory model constructor.
     * @property {module:model/ModelsTickerHistory}
     */
    ModelsTickerHistory,

    /**
     * The ModelsTickerHistoryQuery model constructor.
     * @property {module:model/ModelsTickerHistoryQuery}
     */
    ModelsTickerHistoryQuery,

    /**
    * The DataApi service constructor.
    * @property {module:api/DataApi}
    */
    DataApi
};
