/**
 * FTFP API
 * Finance tools for people
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsTickerHistoryQuery model module.
 * @module model/ModelsTickerHistoryQuery
 * @version 0.0.1
 */
class ModelsTickerHistoryQuery {
    /**
     * Constructs a new <code>ModelsTickerHistoryQuery</code>.
     * @alias module:model/ModelsTickerHistoryQuery
     * @param symbol {String} 
     * @param resolution {String} 
     * @param from {String} 
     * @param to {String} 
     */
    constructor(symbol, resolution, from, to) { 
        
        ModelsTickerHistoryQuery.initialize(this, symbol, resolution, from, to);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, symbol, resolution, from, to) { 
        obj['symbol'] = symbol;
        obj['resolution'] = resolution;
        obj['from'] = from;
        obj['to'] = to;
    }

    /**
     * Constructs a <code>ModelsTickerHistoryQuery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsTickerHistoryQuery} obj Optional instance to populate.
     * @return {module:model/ModelsTickerHistoryQuery} The populated <code>ModelsTickerHistoryQuery</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsTickerHistoryQuery();

            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('resolution')) {
                obj['resolution'] = ApiClient.convertToType(data['resolution'], 'String');
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} symbol
 */
ModelsTickerHistoryQuery.prototype['symbol'] = undefined;

/**
 * @member {String} resolution
 */
ModelsTickerHistoryQuery.prototype['resolution'] = undefined;

/**
 * @member {String} from
 */
ModelsTickerHistoryQuery.prototype['from'] = undefined;

/**
 * @member {String} to
 */
ModelsTickerHistoryQuery.prototype['to'] = undefined;






export default ModelsTickerHistoryQuery;

